#include <cybozu/test.hpp>
#include <xbyak_riscv/xbyak_riscv.hpp>

using namespace Xbyak_riscv;

uint32_t read4ByteLE(const uint8_t *p)
{
	return p[0] | (p[1]<<8) | (p[2]<<16) | (p[3]<<24);
}

uint64_t read8ByteLE(const uint8_t *p)
{
	return read4ByteLE(p) | (uint64_t(read4ByteLE(p + 4))<<32);
}

size_t readBytesLE(const uint8_t *p)
{
	if (sizeof(size_t) == 4) return read4ByteLE(p);
	return read8ByteLE(p);
}

CYBOZU_TEST_AUTO(putL)
{
	struct Code : CodeGenerator {
		size_t Faddr;
		size_t Baddr;
		Code()
		{
			nop();
			Label F, B;
			F = L();
			Faddr = size_t(F.getAddress());
			nop();
			putL(F);
			nop();
			putL(B);
			L(B);
			Baddr = size_t(B.getAddress());
		}
	} c;
	c.ready();
	std::cout << std::hex;
	const size_t codeSize = 4 /*nop*/ * 3 + sizeof(size_t)/*label*/ * 2;
	CYBOZU_TEST_EQUAL(c.getSize(), codeSize);
	uint32_t nop = 0x00000013;
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(read4ByteLE(p), nop);
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 4), nop);
	CYBOZU_TEST_EQUAL(readBytesLE(p + 8), c.Faddr);
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 8 + sizeof(size_t)), nop);
	CYBOZU_TEST_EQUAL(readBytesLE(p + 8 + sizeof(size_t) + 4), c.Baddr);
	std::cout << std::dec;
}



// assignL(dst, src) where dst has not been referenced yet
CYBOZU_TEST_AUTO(assignL_unreferenced_dst)
{
	struct Code : CodeGenerator {
		Code()
		{
			Label src, dst;
			L(src);
			assignL(dst, src);
			CYBOZU_TEST_EQUAL(dst.getAddress(), src.getAddress());
			jal(x0, dst); // backward reference must be resolved
			CYBOZU_TEST_ASSERT(!hasUndefinedLabel());
			// a second assignL with another unreferenced dst must not throw ERR_LABEL_IS_REDEFINED
			Label dst2;
			assignL(dst2, src);
			CYBOZU_TEST_EQUAL(dst2.getAddress(), src.getAddress());
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(read4ByteLE(p), 0x0000006fu); // jal x0, 0
}

// assignL(dst, src) after a forward reference to dst
CYBOZU_TEST_AUTO(assignL_forward_ref)
{
	struct Code : CodeGenerator {
		size_t srcAddr;
		Code()
		{
			Label src, dst;
			jal(x0, dst);      // +0
			beq(x1, x2, dst);  // +4
			putL(dst);         // +8
			L(src);            // +8+sizeof(size_t)
			srcAddr = size_t(src.getAddress());
			nop();
			nop();
			assignL(dst, src); // dst must point to src, not here
			CYBOZU_TEST_EQUAL(dst.getAddress(), src.getAddress());
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	const uint32_t off = 8 + sizeof(size_t);
	// jal x0, off : imm[20|10:1|11|19:12] = (off>>1)<<21
	CYBOZU_TEST_EQUAL(read4ByteLE(p), ((off >> 1) << 21) | 0x6f);
	// beq x1, x2, off-4 : imm[4:1] at [11:8]
	const uint32_t boff = off - 4;
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 4), (((boff >> 1) & 0xf) << 8) | (2 << 20) | (1 << 15) | 0x63);
	CYBOZU_TEST_EQUAL(readBytesLE(p + 8), c.srcAddr);
}

// auipc rt, hi ; jalr rd, lo(rt)
static uint32_t encAuipc(uint32_t rt, uint32_t hi) { return (hi << 12) | (rt << 7) | 0x17; }
static uint32_t encJalr(uint32_t rd, uint32_t rt, uint32_t lo) { return ((lo & 0xfff) << 20) | (rt << 15) | (rd << 7) | 0x67; }

CYBOZU_TEST_AUTO(call_tail_jump)
{
	struct Code : CodeGenerator {
		Code()
		{
			Label B, F, G;
			L(B);                 // +0
			nop();                // +0
			call(B);              // +4 : backward -> jal x1, -4
			call(B, x5);          // +8 : backward -> jal x5, -8
			tail(F);              // +12 : forward
			jump(F, x7);          // +20 : forward
			call(F, x9);          // +28 : forward
			CYBOZU_TEST_ASSERT(hasUndefinedLabel());
			L(F);                 // +36
			CYBOZU_TEST_ASSERT(!hasUndefinedLabel());
			assignL(G, B);
			call(G);              // +36 : off=-36 -> jal x1, -36
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(c.getSize(), size_t(40));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 12), encAuipc(6, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 16), encJalr(0, 6, 24));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 20), encAuipc(7, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 24), encJalr(0, 7, 16));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 28), encAuipc(9, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 32), encJalr(9, 9, 8));
	// machine code generated by gas (riscv64-linux-gnu-as + ld --no-relax)
	// a backward call is relaxed to jal (as ld does with relaxation)
	// call(F, x9) uses rd as a scratch register: gas uses x6
	const uint32_t gas[] = {
		0x00000013,
		0xffdff0ef, // jal x1, B
		0xff9ff2ef, // jal x5, B
		0x00000317, 0x01830067, // tail F
		0x00000397, 0x01038067, // jump F, x7
		0x00000497, 0x008484e7, // auipc x9 ; jalr x9, 8(x9)
		0xfddff0ef, // jal x1, B
	};
	for (size_t i = 0; i < sizeof(gas) / sizeof(gas[0]); i++) {
		CYBOZU_TEST_EQUAL(read4ByteLE(p + i * 4), gas[i]);
	}
}

// a jump to a defined label is compressed if supportRVC()
template<bool rv32>
struct ShortJmpCode : CodeGenerator {
	ShortJmpCode()
	{
		if (rv32) setRV32();
		supportRVC();
		Label B;
		L(B);
		add(x1, x2, x3); // +0 : not compressible
		j_(B);           // +4 : c.j
		jal(x1, B);      // +6 : rv32 ? c.jal : jal x1
		tail(B);         // c.j
		jump(B, x7);     // c.j
		call(B);         // rv32 ? c.jal : jal x1
		call(B, x5);     // jal x5
		beqz(x8, B);     // c.beqz
		bnez(x15, B);    // c.bnez
		beq(x0, x9, B);  // beq (rs1 must not be x0)
		bne(x10, x0, B); // c.bnez
		beqz(x16, B);    // beqz (rs1 must be x8..x15)
		bnez(x7, B);     // bnez
		bne(x8, x9, B);  // bne
		blt(x8, x0, B);  // blt
	}
};

CYBOZU_TEST_AUTO(short_jmp_rvc)
{
	// machine code generated by gas (-march=rv64imafdqvc / rv32imafdc)
	const uint8_t gas64[] = {
		0xb3, 0x00, 0x31, 0x00, 0xf5, 0xbf, 0xef, 0xf0, 0xbf, 0xff, 0xdd, 0xbf,
		0xd5, 0xbf, 0xef, 0xf0, 0x3f, 0xff, 0xef, 0xf2, 0xff, 0xfe, 0x6d, 0xd4,
		0xe5, 0xf7, 0xe3, 0x03, 0x90, 0xfe, 0x6d, 0xf1, 0xe3, 0x00, 0x08, 0xfe,
		0xe3, 0x9e, 0x03, 0xfc, 0xe3, 0x1c, 0x94, 0xfc, 0xe3, 0x4a, 0x04, 0xfc,
	};
	const uint8_t gas32[] = {
		0xb3, 0x00, 0x31, 0x00, 0xf5, 0xbf, 0xed, 0x3f, 0xe5, 0xbf, 0xdd, 0xbf,
		0xd5, 0x3f, 0xef, 0xf2, 0x3f, 0xff, 0x7d, 0xd4, 0xf5, 0xf7, 0xe3, 0x05,
		0x90, 0xfe, 0x7d, 0xf1, 0xe3, 0x02, 0x08, 0xfe, 0xe3, 0x90, 0x03, 0xfe,
		0xe3, 0x1e, 0x94, 0xfc, 0xe3, 0x4c, 0x04, 0xfc,
	};
	{
		ShortJmpCode<false> c;
		c.ready();
		CYBOZU_TEST_EQUAL(c.getSize(), sizeof(gas64));
		CYBOZU_TEST_EQUAL_ARRAY(c.getCode(), gas64, sizeof(gas64));
	}
	{
		ShortJmpCode<true> c;
		c.ready();
		CYBOZU_TEST_EQUAL(c.getSize(), sizeof(gas32));
		CYBOZU_TEST_EQUAL_ARRAY(c.getCode(), gas32, sizeof(gas32));
	}
}

// boundary of the range of each short form (the label is behind)
CYBOZU_TEST_AUTO(short_jmp_range)
{
	const uint8_t *from = reinterpret_cast<const uint8_t*>(size_t(0x10000000));
	const struct {
		int64_t off;
		size_t sizeRvc; // size with supportRVC
		size_t size;    // size without supportRVC
	} tbl[] = {
		{ -2, 2, 4 },
		{ -2048, 2, 4 },    // c.j min
		{ -2050, 4, 4 },
		{ 2046, 2, 4 },     // c.j max
		{ 2048, 4, 4 },
		{ -(1 << 20), 4, 4 }, // jal min
		{ -(1 << 20) - 2, 8, 8 },
		{ (1 << 20) - 2, 4, 4 }, // jal max
		{ (1 << 20), 8, 8 },
	};
	for (size_t i = 0; i < sizeof(tbl) / sizeof(tbl[0]); i++) {
		uint64_t code;
		Jmp tail(from, x6, 0x67, 0, x0);
		CYBOZU_TEST_EQUAL(tail.encodeShort(&code, from + tbl[i].off, true, false), tbl[i].sizeRvc);
		CYBOZU_TEST_EQUAL(tail.encodeShort(&code, from + tbl[i].off, false, false), tbl[i].size);
		// c.jal only on RV32
		Jmp call(from, x1, 0x67, 0, x1);
		CYBOZU_TEST_EQUAL(call.encodeShort(&code, from + tbl[i].off, true, true), tbl[i].sizeRvc);
		CYBOZU_TEST_EQUAL(call.encodeShort(&code, from + tbl[i].off, true, false), tbl[i].sizeRvc == 2 ? 4 : tbl[i].sizeRvc);
		// la is never shortened
		Jmp la(from, x1, 0x13, 0, x1);
		CYBOZU_TEST_EQUAL(la.encodeShort(&code, from + tbl[i].off, true, true), 8u);
	}
	const struct {
		int64_t off;
		size_t sizeRvc;
	} btbl[] = {
		{ -2, 2 },
		{ -256, 2 }, // c.beqz min
		{ -258, 4 },
		{ 254, 2 },  // c.beqz max
		{ 256, 4 },
	};
	for (size_t i = 0; i < sizeof(btbl) / sizeof(btbl[0]); i++) {
		uint64_t code;
		Jmp beqz(from, 0x63, 0, x8, x0);
		CYBOZU_TEST_EQUAL(beqz.encodeShort(&code, from + btbl[i].off, true, false), btbl[i].sizeRvc);
		CYBOZU_TEST_EQUAL(beqz.encodeShort(&code, from + btbl[i].off, false, false), 4u);
	}
}

// hi20 must be adjusted when lo12 is negative
CYBOZU_TEST_AUTO(call_hi_lo_split)
{
	const uint8_t *from = reinterpret_cast<const uint8_t*>(size_t(0x10000000));
	const struct {
		int64_t off;
		uint32_t hi, lo;
	} tbl[] = {
		{ 0, 0, 0 },
		{ 0x7ff, 0, 0x7ff },
		{ 0x800, 1, 0x800 }, // lo=-2048, hi=1
		{ 0xfff, 1, 0xfff }, // lo=-1, hi=1
		{ 0x1000, 1, 0 },
		{ -1, 0, 0xfff },
		{ -0x800, 0, 0x800 },
		{ -0x801, 0xfffff, 0x7ff },
		{ -0x1000, 0xfffff, 0 },
		{ 0x12345678, 0x12345, 0x678 },
		{ 0x12345abc, 0x12346, 0xabc },
		{ int64_t(0x7ffff7ff), 0x7ffff, 0x7ff }, // max
		{ -int64_t(0x80000800), 0x80000, 0x800 }, // min
	};
	for (size_t i = 0; i < sizeof(tbl) / sizeof(tbl[0]); i++) {
		Jmp jmp(from, x6, 0x67, 0, x0); // tail
		uint64_t v = jmp.encode(from + tbl[i].off);
		CYBOZU_TEST_EQUAL(uint32_t(v), encAuipc(6, tbl[i].hi));
		CYBOZU_TEST_EQUAL(uint32_t(v >> 32), encJalr(0, 6, tbl[i].lo));
	}
	// out of range
	const int64_t badTbl[] = { int64_t(0x7ffff800), -int64_t(0x80000801) };
	for (size_t i = 0; i < 2; i++) {
		Jmp jmp(from, x1, 0x67, 0, x1);
		CYBOZU_TEST_EXCEPTION(jmp.encode(from + badTbl[i]), std::exception);
	}
}

// la(label, rd) : auipc rd, hi ; addi rd, rd, lo
CYBOZU_TEST_AUTO(la)
{
	struct Code : CodeGenerator {
		Code()
		{
			Label B, F;
			L(B);
			nop();       // +0
			la(B, x1);   // +4
			la(F, x10);  // +12 : forward
			nop();       // +20
			L(F);        // +24
			la(B, x31);  // +24
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(c.getSize(), size_t(32));
	// machine code generated by gas (riscv64-linux-gnu-as + ld --no-relax, .option nopic)
	const uint32_t gas[] = {
		0x00000013,
		0x00000097, 0xffc08093, // la x1, B
		0x00000517, 0x00c50513, // la x10, F
		0x00000013,
		0x00000f97, 0xfe8f8f93, // la x31, B
	};
	for (size_t i = 0; i < sizeof(gas) / sizeof(gas[0]); i++) {
		CYBOZU_TEST_EQUAL(read4ByteLE(p + i * 4), gas[i]);
	}
}
