#include <cybozu/test.hpp>
#include <xbyak_riscv/xbyak_riscv.hpp>

using namespace Xbyak_riscv;

uint32_t read4ByteLE(const uint8_t *p)
{
	return p[0] | (p[1]<<8) | (p[2]<<16) | (p[3]<<24);
}

uint64_t read8ByteLE(const uint8_t *p)
{
	return read4ByteLE(p) | (uint64_t(read4ByteLE(p + 4))<<32);
}

size_t readBytesLE(const uint8_t *p)
{
	if (sizeof(size_t) == 4) return read4ByteLE(p);
	return read8ByteLE(p);
}

CYBOZU_TEST_AUTO(putL)
{
	struct Code : CodeGenerator {
		size_t Faddr;
		size_t Baddr;
		Code()
		{
			nop();
			Label F, B;
			F = L();
			Faddr = size_t(F.getAddress());
			nop();
			putL(F);
			nop();
			putL(B);
			L(B);
			Baddr = size_t(B.getAddress());
		}
	} c;
	c.ready();
	std::cout << std::hex;
	const size_t codeSize = 4 /*nop*/ * 3 + sizeof(size_t)/*label*/ * 2;
	CYBOZU_TEST_EQUAL(c.getSize(), codeSize);
	uint32_t nop = 0x00000013;
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(read4ByteLE(p), nop);
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 4), nop);
	CYBOZU_TEST_EQUAL(readBytesLE(p + 8), c.Faddr);
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 8 + sizeof(size_t)), nop);
	CYBOZU_TEST_EQUAL(readBytesLE(p + 8 + sizeof(size_t) + 4), c.Baddr);
	std::cout << std::dec;
}



// assignL(dst, src) where dst has not been referenced yet
CYBOZU_TEST_AUTO(assignL_unreferenced_dst)
{
	struct Code : CodeGenerator {
		Code()
		{
			Label src, dst;
			L(src);
			assignL(dst, src);
			CYBOZU_TEST_EQUAL(dst.getAddress(), src.getAddress());
			jal(x0, dst); // backward reference must be resolved
			CYBOZU_TEST_ASSERT(!hasUndefinedLabel());
			// a second assignL with another unreferenced dst must not throw ERR_LABEL_IS_REDEFINED
			Label dst2;
			assignL(dst2, src);
			CYBOZU_TEST_EQUAL(dst2.getAddress(), src.getAddress());
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(read4ByteLE(p), 0x0000006fu); // jal x0, 0
}

// assignL(dst, src) after a forward reference to dst
CYBOZU_TEST_AUTO(assignL_forward_ref)
{
	struct Code : CodeGenerator {
		size_t srcAddr;
		Code()
		{
			Label src, dst;
			jal(x0, dst);      // +0
			beq(x1, x2, dst);  // +4
			putL(dst);         // +8
			L(src);            // +8+sizeof(size_t)
			srcAddr = size_t(src.getAddress());
			nop();
			nop();
			assignL(dst, src); // dst must point to src, not here
			CYBOZU_TEST_EQUAL(dst.getAddress(), src.getAddress());
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	const uint32_t off = 8 + sizeof(size_t);
	// jal x0, off : imm[20|10:1|11|19:12] = (off>>1)<<21
	CYBOZU_TEST_EQUAL(read4ByteLE(p), ((off >> 1) << 21) | 0x6f);
	// beq x1, x2, off-4 : imm[4:1] at [11:8]
	const uint32_t boff = off - 4;
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 4), (((boff >> 1) & 0xf) << 8) | (2 << 20) | (1 << 15) | 0x63);
	CYBOZU_TEST_EQUAL(readBytesLE(p + 8), c.srcAddr);
}

// auipc rt, hi ; jalr rd, lo(rt)
static uint32_t encAuipc(uint32_t rt, uint32_t hi) { return (hi << 12) | (rt << 7) | 0x17; }
static uint32_t encJalr(uint32_t rd, uint32_t rt, uint32_t lo) { return ((lo & 0xfff) << 20) | (rt << 15) | (rd << 7) | 0x67; }

CYBOZU_TEST_AUTO(call_tail_jump)
{
	struct Code : CodeGenerator {
		Code()
		{
			Label B, F, G;
			L(B);                 // +0
			nop();                // +0
			call(B);              // +4 : off=-4  -> hi=0, lo=-4
			call(B, x5);          // +12 : off=-12
			tail(F);              // +20 : forward
			jump(F, x7);          // +28 : forward
			call(F, x9);          // +36 : forward
			CYBOZU_TEST_ASSERT(hasUndefinedLabel());
			L(F);                 // +44
			CYBOZU_TEST_ASSERT(!hasUndefinedLabel());
			assignL(G, B);
			call(G);              // +44 : off=-44
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(c.getSize(), size_t(52));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 4), encAuipc(1, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 8), encJalr(1, 1, uint32_t(-4)));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 12), encAuipc(5, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 16), encJalr(5, 5, uint32_t(-12)));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 20), encAuipc(6, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 24), encJalr(0, 6, 24));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 28), encAuipc(7, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 32), encJalr(0, 7, 16));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 36), encAuipc(9, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 40), encJalr(9, 9, 8));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 44), encAuipc(1, 0));
	CYBOZU_TEST_EQUAL(read4ByteLE(p + 48), encJalr(1, 1, uint32_t(-44)));
	// machine code generated by gas (riscv64-linux-gnu-as + ld --no-relax)
	// call(B, x5) and call(F, x9) use rd as a scratch register: gas uses x6
	const uint32_t gas[] = {
		0x00000013,
		0x00000097, 0xffc080e7, // call B
		0x00000297, 0xff4282e7, // auipc x5 ; jalr x5, -12(x5)
		0x00000317, 0x01830067, // tail F
		0x00000397, 0x01038067, // jump F, x7
		0x00000497, 0x008484e7, // auipc x9 ; jalr x9, 8(x9)
		0x00000097, 0xfd4080e7, // call B
	};
	for (size_t i = 0; i < sizeof(gas) / sizeof(gas[0]); i++) {
		CYBOZU_TEST_EQUAL(read4ByteLE(p + i * 4), gas[i]);
	}
}

// hi20 must be adjusted when lo12 is negative
CYBOZU_TEST_AUTO(call_hi_lo_split)
{
	const uint8_t *from = reinterpret_cast<const uint8_t*>(size_t(0x10000000));
	const struct {
		int64_t off;
		uint32_t hi, lo;
	} tbl[] = {
		{ 0, 0, 0 },
		{ 0x7ff, 0, 0x7ff },
		{ 0x800, 1, 0x800 }, // lo=-2048, hi=1
		{ 0xfff, 1, 0xfff }, // lo=-1, hi=1
		{ 0x1000, 1, 0 },
		{ -1, 0, 0xfff },
		{ -0x800, 0, 0x800 },
		{ -0x801, 0xfffff, 0x7ff },
		{ -0x1000, 0xfffff, 0 },
		{ 0x12345678, 0x12345, 0x678 },
		{ 0x12345abc, 0x12346, 0xabc },
		{ int64_t(0x7ffff7ff), 0x7ffff, 0x7ff }, // max
		{ -int64_t(0x80000800), 0x80000, 0x800 }, // min
	};
	for (size_t i = 0; i < sizeof(tbl) / sizeof(tbl[0]); i++) {
		Jmp jmp(from, x6, 0x67, 0, x0); // tail
		uint64_t v = jmp.encode(from + tbl[i].off);
		CYBOZU_TEST_EQUAL(uint32_t(v), encAuipc(6, tbl[i].hi));
		CYBOZU_TEST_EQUAL(uint32_t(v >> 32), encJalr(0, 6, tbl[i].lo));
	}
	// out of range
	const int64_t badTbl[] = { int64_t(0x7ffff800), -int64_t(0x80000801) };
	for (size_t i = 0; i < 2; i++) {
		Jmp jmp(from, x1, 0x67, 0, x1);
		CYBOZU_TEST_EXCEPTION(jmp.encode(from + badTbl[i]), std::exception);
	}
}

// la(label, rd) : auipc rd, hi ; addi rd, rd, lo
CYBOZU_TEST_AUTO(la)
{
	struct Code : CodeGenerator {
		Code()
		{
			Label B, F;
			L(B);
			nop();       // +0
			la(B, x1);   // +4
			la(F, x10);  // +12 : forward
			nop();       // +20
			L(F);        // +24
			la(B, x31);  // +24
		}
	} c;
	c.ready();
	const uint8_t *p = c.getCode();
	CYBOZU_TEST_EQUAL(c.getSize(), size_t(32));
	// machine code generated by gas (riscv64-linux-gnu-as + ld --no-relax, .option nopic)
	const uint32_t gas[] = {
		0x00000013,
		0x00000097, 0xffc08093, // la x1, B
		0x00000517, 0x00c50513, // la x10, F
		0x00000013,
		0x00000f97, 0xfe8f8f93, // la x31, B
	};
	for (size_t i = 0; i < sizeof(gas) / sizeof(gas[0]); i++) {
		CYBOZU_TEST_EQUAL(read4ByteLE(p + i * 4), gas[i]);
	}
}
